[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
program_derived_addresses = ""

[registry]
url = "http://127.0.0.1:8899"

[provider]
cluster = "localnet"                    # The cluster used for all commands.
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
